name: geography

services:
  postgres:
    image: postgres:15-alpine
    container_name: geography-postgres
    environment:
      POSTGRES_DB: GEOGRAPHY
      POSTGRES_USER: geography_user
      POSTGRES_PASSWORD: geography_password
    ports:
      - "5438:5432"
    volumes:
      - geography_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geography_user -d GEOGRAPHY"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  geography_data:


  ### este docker se hizo  con el fin de  interpretar un modelo de datos existente (funcional)